//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileBook.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfileBook.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Take photo with camera.
        /// </summary>
        public static string AddEditProfilePage_ActionSheetCamera {
            get {
                return ResourceManager.GetString("AddEditProfilePage_ActionSheetCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick at Gallery.
        /// </summary>
        public static string AddEditProfilePage_ActionSheetGallery {
            get {
                return ResourceManager.GetString("AddEditProfilePage_ActionSheetGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обрати фото.
        /// </summary>
        public static string AddEditProfilePage_ActionSheetTitle {
            get {
                return ResourceManager.GetString("AddEditProfilePage_ActionSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string AddEditProfilePage_DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("AddEditProfilePage_DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string AddEditProfilePage_NamePlaceholder {
            get {
                return ResourceManager.GetString("AddEditProfilePage_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NickName.
        /// </summary>
        public static string AddEditProfilePage_NickPlaceholder {
            get {
                return ResourceManager.GetString("AddEditProfilePage_NickPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Profile.
        /// </summary>
        public static string AddEditProfilePage_Title {
            get {
                return ResourceManager.GetString("AddEditProfilePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string MainListPage_AlertCancel {
            get {
                return ResourceManager.GetString("MainListPage_AlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string MainListPage_AlertOk {
            get {
                return ResourceManager.GetString("MainListPage_AlertOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete profile.
        /// </summary>
        public static string MainListPage_AlertTitle {
            get {
                return ResourceManager.GetString("MainListPage_AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string MainListPage_ContextmenuDelete {
            get {
                return ResourceManager.GetString("MainListPage_ContextmenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string MainListPage_ContextmenuEdit {
            get {
                return ResourceManager.GetString("MainListPage_ContextmenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No profiles added.
        /// </summary>
        public static string MainListPage_Label {
            get {
                return ResourceManager.GetString("MainListPage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main List.
        /// </summary>
        public static string MainListPage_Title {
            get {
                return ResourceManager.GetString("MainListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SAVE.
        /// </summary>
        public static string SettingsPage_Button {
            get {
                return ResourceManager.GetString("SettingsPage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string SettingsPage_CheckboxLabelDark {
            get {
                return ResourceManager.GetString("SettingsPage_CheckboxLabelDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Localization.
        /// </summary>
        public static string SettingsPage_LabelLocalization {
            get {
                return ResourceManager.GetString("SettingsPage_LabelLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort by.
        /// </summary>
        public static string SettingsPage_LabelSort {
            get {
                return ResourceManager.GetString("SettingsPage_LabelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string SettingsPage_LabelTheme {
            get {
                return ResourceManager.GetString("SettingsPage_LabelTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string SettingsPage_RadiobuttonDate {
            get {
                return ResourceManager.GetString("SettingsPage_RadiobuttonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string SettingsPage_RadiobuttonName {
            get {
                return ResourceManager.GetString("SettingsPage_RadiobuttonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NickName.
        /// </summary>
        public static string SettingsPage_RadiobuttonNick {
            get {
                return ResourceManager.GetString("SettingsPage_RadiobuttonNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid login or password!.
        /// </summary>
        public static string SingInPage_Alert {
            get {
                return ResourceManager.GetString("SingInPage_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SING IN.
        /// </summary>
        public static string SingInPage_Button {
            get {
                return ResourceManager.GetString("SingInPage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SING UP.
        /// </summary>
        public static string SingInPage_Label {
            get {
                return ResourceManager.GetString("SingInPage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string SingInPage_LoginPlaceholder {
            get {
                return ResourceManager.GetString("SingInPage_LoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string SingInPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("SingInPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users SingIn.
        /// </summary>
        public static string SingInPage_Title {
            get {
                return ResourceManager.GetString("SingInPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login must be at least 4 and no more than 16 symbols!.
        /// </summary>
        public static string SingUpPage_AlertLoginLength {
            get {
                return ResourceManager.GetString("SingUpPage_AlertLoginLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This login is already taken!.
        /// </summary>
        public static string SingUpPage_AlertLoginMatch {
            get {
                return ResourceManager.GetString("SingUpPage_AlertLoginMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login musn&apos;t start with numbers!.
        /// </summary>
        public static string SingUpPage_AlertLoginNumbers {
            get {
                return ResourceManager.GetString("SingUpPage_AlertLoginNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords must match!.
        /// </summary>
        public static string SingUpPage_AlertPasswordMatch {
            get {
                return ResourceManager.GetString("SingUpPage_AlertPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password must be at least 8 and no more than 16 symbols and must contain at least one uppercase letter, one lowercase letter and one number!.
        /// </summary>
        public static string SingUpPage_AlertPasswordValid {
            get {
                return ResourceManager.GetString("SingUpPage_AlertPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SING UP.
        /// </summary>
        public static string SingUpPage_Button {
            get {
                return ResourceManager.GetString("SingUpPage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string SingUpPage_LoginPlaceholder {
            get {
                return ResourceManager.GetString("SingUpPage_LoginPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string SingUpPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("SingUpPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm Password.
        /// </summary>
        public static string SingUpPage_SecondPasswordPlaceholder {
            get {
                return ResourceManager.GetString("SingUpPage_SecondPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users SingUp.
        /// </summary>
        public static string SingUpPage_Title {
            get {
                return ResourceManager.GetString("SingUpPage_Title", resourceCulture);
            }
        }
    }
}
